---
- name: Pull and run my calculator CLI Docker image
  hosts: localhost
  gather_facts: false
  vars:
    # Use Python from the venv
    ansible_python_interpreter: /Users/bhavyakapadia/ansible-venv/bin/python3

  tasks:

    - name: Check if Docker is running
      ansible.builtin.command: docker info
      register: docker_status
      ignore_errors: yes

    - name: Fail if Docker is not running
      ansible.builtin.fail:
        msg: "Docker is not running. Please start Docker Desktop before running this playbook."
      when: docker_status.rc != 0

    - name: Pull my Docker image
      community.docker.docker_image:
        name: bkapadia04/calculator-spe-mini-project:latest
        source: pull

    - name: Remove existing container if present
      community.docker.docker_container:
        name: calculator-cli
        state: absent
        force_kill: true

    - name: Run my container in detached mode
      community.docker.docker_container:
        name: calculator-cli
        image: bkapadia04/calculator-spe-mini-project:latest
        state: started
        restart: yes
        interactive: true
        tty: true
        detach: yes

    - name: Run the calculator CLI app inside the container
      ansible.builtin.command: docker exec -it calculator-cli java -jar app.jar